num_steps: 50000000  # It equals to 200M frames.
batch_size: 32
N: 32
N_dash: 32
K: 32
num_cosines: 64
kappa: 1.0
lr: 5.e-4
memory_size: 1000000
gamma: 0.99
multi_step: 1
update_interval: 4
target_update_interval: 1000
start_steps: 1000000
epsilon_train: 0.01
epsilon_eval: 0.001
epsilon_decay_steps: 1000000  # It equals to 1M frames.
log_interval: 100
eval_interval: 100000
num_eval_steps: 100000  # It equals to 500k frames.
max_episode_steps: 1000
grad_cliping:
eta0: 0
eta1: 0.05