num_steps: 50000000  # It equals to 200M frames.
num_taus: 64
c: 0.05
lr: 0.1
gamma: 1
multi_step: 1
update_interval: 4
target_update_interval: 1
start_steps: 1
epsilon_train: 0.01
epsilon_eval: 0.00
epsilon_decay_steps: 100000  # It equals to 1M frames.
log_interval: 100
eval_interval: 1000000
num_eval_steps: 1000  # It equals to 500k frames.
max_episode_steps: 100
